package com.seckilling.dao;

import com.seckilling.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun May 26 14:47:15 PDT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun May 26 14:47:15 PDT 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun May 26 14:47:15 PDT 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun May 26 14:47:15 PDT 2019
     */
    ItemDO selectByPrimaryKey(Integer id);


    List<ItemDO> selectAllItems();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun May 26 14:47:15 PDT 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun May 26 14:47:15 PDT 2019
     */
    int updateByPrimaryKey(ItemDO record);


    //Since we have more than 1 params, need to use @Param
    int increaseSales(@Param("id") Integer id, @Param("quantity") Integer quantity);
}